name: Victor Algaze
author: Victor Algaze

description: Software Engineer
github: http://www.github.com/valgaze
twitter: http://www.twitter.com/valgaze
facebook: http://www.facebook.com/victoralgaze
linkedin: http://www.linkedin.com/in/victoralgaze
email: valgaze[at]gmail.com
permalink: pretty
disqus: victoralgaze
##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

authors:
  victor:
    display_name: Victor Algaze
    gravatar: b5ccb62439c9abfa1570d738946a3636
    email: valgaze@gmail.com




defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
