name: Victor Algaze
author: Victor Algaze

description: Software Engineer
github: http://www.github.com/valgaze
twitter: http://www.twitter.com/valgaze
facebook: http://www.facebook.com/victoralgaze
linkedin: http://www.linkedin.com/in/victoralgaze
email: valgaze[at]gmail.com
permalink: pretty
##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
